contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #assemblypipeline channel"
    url: https://nfcore.slack.com/channels/assemblypipeline
    about: Discussion about the nf-core/assemblypipeline pipeline
